# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3ba9f0dc-edc3-4067-9150-708d69a9af69";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zlib:9" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3ba9f0dc-edc3-4067-9150-708d69a9af69";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zlib:9" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3ba9f0dc-edc3-4067-9150-708d69a9af69";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zlib:9" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
